# Generated by Django 5.0.4 on 2024-04-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_applicant_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.CharField(),
        ),
    ]
