# Generated by Django 5.0.4 on 2024-04-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_applicant_title_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contactnumber',
            field=models.IntegerField(),
        ),
    ]
