# Generated by Django 5.0.4 on 2024-04-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_at',
            new_name='posted_on',
        ),
    ]
