# Generated by Django 5.0.4 on 2024-04-17 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_applicant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='skills',
        ),
        migrations.AlterField(
            model_name='certification',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.applicant'),
        ),
        migrations.AlterField(
            model_name='education',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.applicant'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.applicant'),
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('H', 'HTML'), ('C', 'CSS'), ('J', 'Javascript'), ('N', 'Node.js'), ('R', 'React'), ('E', 'Express'), ('P', 'Python'), ('D', 'Django'), ('M', 'MongoDB'), ('S', 'SQL')], default='H', max_length=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.applicant')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
