# Generated by Django 5.0.4 on 2024-04-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_applicant_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='skillset',
            name='skill',
            field=models.CharField(choices=[('H', 'HTML'), ('C', 'CSS'), ('J', 'Javascript'), ('N', 'Node.js'), ('R', 'React'), ('E', 'Express'), ('P', 'Python'), ('D', 'Django'), ('M', 'MongoDB'), ('S', 'SQL')], default='H', max_length=1),
        ),
    ]
