# Generated by Django 5.0.4 on 2024-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_title_job_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='about_company',
        ),
        migrations.AddField(
            model_name='job',
            name='ideal_candidate',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirements',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
