# Generated by Django 5.0.4 on 2024-04-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_certification_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='description',
        ),
    ]
